spring.application.name=apollon-backend

# Datenbank-Verbindung
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# MQTT-Verbindung
apollon.mqtt.broker-url=${SPRING_MQTT_BROKER_URL}
apollon.mqtt.client-id=${SPRING_MQTT_CLIENT_ID}

# Automatisches Anlegen der Tabellen
spring.jpa.hibernate.ddl-auto=update